{
  "formatVersion": "1.1",
  "component": {
    "group": "com.x8zs.adsdk",
    "module": "x851cn",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "24jwabt75bclzikzsc2zmxfs3m"
    }
  },
  "variants": [
    {
      "name": "x851cnReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "x851cn-1.1.1.aar",
          "url": "x851cn-1.1.1.aar",
          "size": 264886,
          "sha512": "0138f924e9181cd549b5a35006df402eeee5ad5b694fb043a94f98696db304728551ea21a869f42953d48c40c932012557e60dfa72fb332c92b2734253b2b7ad",
          "sha256": "c7ab6bb7560d0e2a6803e7f1917aeb1e49934d98c58aca66e7b4fc1d9430117a",
          "sha1": "38adaf746efd2dacfcb426623dc1ad4f819c2bc6",
          "md5": "cd8e17e870e3f1db17b180369807c9d9"
        }
      ]
    },
    {
      "name": "x851cnReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pangle.cn.m",
          "module": "mediation-sdk",
          "version": {
            "requires": "6.2.1.7"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-test-tools",
          "version": {
            "requires": "6.2.1.7"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-gdt-adapter",
          "version": {
            "requires": "4.575.1445.1"
          }
        },
        {
          "group": "com.qq.e.union.m",
          "module": "union",
          "version": {
            "requires": "4.575.1445"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-baidu-adapter",
          "version": {
            "requires": "9.35.1"
          }
        },
        {
          "group": "com.baidu.mobads",
          "module": "mobads",
          "version": {
            "requires": "9.35"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-ks-adapter",
          "version": {
            "requires": "3.3.63.2"
          }
        },
        {
          "group": "com.kwad.sdk",
          "module": "kssdk-ad",
          "version": {
            "requires": "3.3.63"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-sigmob-adapter",
          "version": {
            "requires": "4.17.1.1"
          }
        },
        {
          "group": "com.sigmob.sdk",
          "module": "common",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.sigmob.sdk",
          "module": "adsdk",
          "version": {
            "requires": "4.17.1"
          }
        },
        {
          "group": "com.beizi",
          "module": "fusion",
          "version": {
            "requires": "4.90.4.12"
          }
        },
        {
          "group": "com.beizi",
          "module": "adsdk",
          "version": {
            "requires": "3.5.0.11"
          }
        },
        {
          "group": "doublejump.top",
          "module": "channel",
          "version": {
            "requires": "1.1.28"
          }
        },
        {
          "group": "doublejump.top",
          "module": "zhike",
          "version": {
            "requires": "1.1.28"
          }
        },
        {
          "group": "doublejump.top",
          "module": "base",
          "version": {
            "requires": "1.1.13"
          }
        },
        {
          "group": "doublejump.top",
          "module": "adsdk",
          "version": {
            "requires": "1.1.28"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcode",
          "version": {
            "requires": "1.25.8"
          }
        },
        {
          "group": "me.drakeet.support",
          "module": "toastcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "x851cn-1.1.1.aar",
          "url": "x851cn-1.1.1.aar",
          "size": 264886,
          "sha512": "0138f924e9181cd549b5a35006df402eeee5ad5b694fb043a94f98696db304728551ea21a869f42953d48c40c932012557e60dfa72fb332c92b2734253b2b7ad",
          "sha256": "c7ab6bb7560d0e2a6803e7f1917aeb1e49934d98c58aca66e7b4fc1d9430117a",
          "sha1": "38adaf746efd2dacfcb426623dc1ad4f819c2bc6",
          "md5": "cd8e17e870e3f1db17b180369807c9d9"
        }
      ]
    }
  ]
}
