{
  "formatVersion": "1.1",
  "component": {
    "group": "com.x8zs.adsdk",
    "module": "hlx",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "327adasfn5flffyu5sxhimjvxe"
    }
  },
  "variants": [
    {
      "name": "hlxReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hlx-1.1.aar",
          "url": "hlx-1.1.aar",
          "size": 109331,
          "sha512": "1948258c109208a3f12600bba2e20b42846252da14f220ba245f25b559280a412e35b7370e8b048da45418f0af00e5eeabd202db33ff0cfce9e4b7f4972d6996",
          "sha256": "b4525ecc9772ef124f3126b07c775fc360e926937c02cd1f1e07960fcada270e",
          "sha1": "1c0b554001edb9bf91f35b3cb82a697b084e7bc1",
          "md5": "bb18170e6745f7b4e9dcc6cc61457c2c"
        }
      ]
    },
    {
      "name": "hlxReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pangle.cn.m",
          "module": "mediation-sdk",
          "version": {
            "requires": "6.2.1.7"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-test-tools",
          "version": {
            "requires": "6.2.1.7"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcode",
          "version": {
            "requires": "1.25.8"
          }
        },
        {
          "group": "me.drakeet.support",
          "module": "toastcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "hlx-1.1.aar",
          "url": "hlx-1.1.aar",
          "size": 109331,
          "sha512": "1948258c109208a3f12600bba2e20b42846252da14f220ba245f25b559280a412e35b7370e8b048da45418f0af00e5eeabd202db33ff0cfce9e4b7f4972d6996",
          "sha256": "b4525ecc9772ef124f3126b07c775fc360e926937c02cd1f1e07960fcada270e",
          "sha1": "1c0b554001edb9bf91f35b3cb82a697b084e7bc1",
          "md5": "bb18170e6745f7b4e9dcc6cc61457c2c"
        }
      ]
    }
  ]
}
