{
  "formatVersion": "1.1",
  "component": {
    "group": "com.x8zs.adsdk",
    "module": "x851cn",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2eq6ldyp7bbkdcurfrkk5mljpq"
    }
  },
  "variants": [
    {
      "name": "x851cnReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "x851cn-1.2.0.aar",
          "url": "x851cn-1.2.0.aar",
          "size": 259687,
          "sha512": "8e327d52bb197a26f2d76f54e1866f739d178163c3e7e931b988217dfbd92b6b4a795425de0912e32fda095f783e5229923f8f05b9d7d04659405aa144ee65fc",
          "sha256": "bab67c42d6a5fe17c3407c4a1bde1f2472e1c2f9459bf17bf74b66a28e7fcea1",
          "sha1": "74ef99e221a469cc8af3f9c6fcd7d87c3b26bbf5",
          "md5": "1ad920017ca6f6782bfd896f1a3762ab"
        }
      ]
    },
    {
      "name": "x851cnReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pangle.cn.m",
          "module": "mediation-sdk",
          "version": {
            "requires": "6.6.0.7"
          }
        },
        {
          "group": "com.pangle.cn.m",
          "module": "mediation-test-tools",
          "version": {
            "requires": "6.6.0.7"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-gdt-adapter",
          "version": {
            "requires": "4.610.1480.0"
          }
        },
        {
          "group": "com.qq.e.union.m",
          "module": "union",
          "version": {
            "requires": "4.610.1480"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-baidu-adapter",
          "version": {
            "requires": "9.37.3"
          }
        },
        {
          "group": "com.baidu.mobads",
          "module": "mobads",
          "version": {
            "requires": "9.37"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-ks-adapter",
          "version": {
            "requires": "3.3.69.3"
          }
        },
        {
          "group": "com.kwad.sdk",
          "module": "kssdk-ad",
          "version": {
            "requires": "3.3.69"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-sigmob-adapter",
          "version": {
            "requires": "4.19.5.0"
          }
        },
        {
          "group": "com.sigmob.sdk",
          "module": "common",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "com.sigmob.sdk",
          "module": "adsdk",
          "version": {
            "requires": "4.19.5"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcode",
          "version": {
            "requires": "1.25.8"
          }
        },
        {
          "group": "me.drakeet.support",
          "module": "toastcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "x851cn-1.2.0.aar",
          "url": "x851cn-1.2.0.aar",
          "size": 259687,
          "sha512": "8e327d52bb197a26f2d76f54e1866f739d178163c3e7e931b988217dfbd92b6b4a795425de0912e32fda095f783e5229923f8f05b9d7d04659405aa144ee65fc",
          "sha256": "bab67c42d6a5fe17c3407c4a1bde1f2472e1c2f9459bf17bf74b66a28e7fcea1",
          "sha1": "74ef99e221a469cc8af3f9c6fcd7d87c3b26bbf5",
          "md5": "1ad920017ca6f6782bfd896f1a3762ab"
        }
      ]
    }
  ]
}
