{
  "formatVersion": "1.1",
  "component": {
    "group": "com.x8zs.adsdk",
    "module": "hlx",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ullurj3jibegtjpuqtoqr36ina"
    }
  },
  "variants": [
    {
      "name": "hlxReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hlx-1.1.2.aar",
          "url": "hlx-1.1.2.aar",
          "size": 107883,
          "sha512": "d70458073b920bdbc93e4034a680d4a0d3e1e8b4b78beee93be14c1244e140d78dd2b03c495af6854b2006b9291f5a1ffe18c1c28033554db0aa4b24175014ab",
          "sha256": "87a63d98426e7dfaf885cf000ddabffd02c48e8f77af756acb928c21b6750838",
          "sha1": "35206f545a4a3bfe08ff33d6e51638d373a1ec4a",
          "md5": "0aa995fbf512ca24ad83ee510879ead2"
        }
      ]
    },
    {
      "name": "hlxReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pangle.cn.m",
          "module": "mediation-sdk",
          "version": {
            "requires": "6.2.1.7"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-test-tools",
          "version": {
            "requires": "6.2.1.7"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcode",
          "version": {
            "requires": "1.25.8"
          }
        },
        {
          "group": "me.drakeet.support",
          "module": "toastcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "hlx-1.1.2.aar",
          "url": "hlx-1.1.2.aar",
          "size": 107883,
          "sha512": "d70458073b920bdbc93e4034a680d4a0d3e1e8b4b78beee93be14c1244e140d78dd2b03c495af6854b2006b9291f5a1ffe18c1c28033554db0aa4b24175014ab",
          "sha256": "87a63d98426e7dfaf885cf000ddabffd02c48e8f77af756acb928c21b6750838",
          "sha1": "35206f545a4a3bfe08ff33d6e51638d373a1ec4a",
          "md5": "0aa995fbf512ca24ad83ee510879ead2"
        }
      ]
    }
  ]
}
