{
  "formatVersion": "1.1",
  "component": {
    "group": "com.x8zs.adsdk",
    "module": "x851cn",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6huveefbcbc45dzom5phbos5rm"
    }
  },
  "variants": [
    {
      "name": "x851cnReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "x851cn-1.1.aar",
          "url": "x851cn-1.1.aar",
          "size": 264851,
          "sha512": "cb27d10357c6047b5c76f95d2b323909afa1aaa8141f930a86937cc1d4f95023599ed1056d901edb322dcf7aa77397f8aa162c667a2557f19d6aa384904df7e4",
          "sha256": "8bbb77c0775884035ab949a90b63f29a4feafc46a85e14967aac1bb013639884",
          "sha1": "1a129aafa64cc502dd438f889fd1b4c41f6cdefb",
          "md5": "4eaf4dca03210416b98a93791d3ca0e3"
        }
      ]
    },
    {
      "name": "x851cnReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pangle.cn.m",
          "module": "mediation-sdk",
          "version": {
            "requires": "6.2.1.7"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-test-tools",
          "version": {
            "requires": "6.2.1.7"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-gdt-adapter",
          "version": {
            "requires": "4.575.1445.1"
          }
        },
        {
          "group": "com.qq.e.union.m",
          "module": "union",
          "version": {
            "requires": "4.575.1445"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-baidu-adapter",
          "version": {
            "requires": "9.35.1"
          }
        },
        {
          "group": "com.baidu.mobads",
          "module": "mobads",
          "version": {
            "requires": "9.35"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-ks-adapter",
          "version": {
            "requires": "3.3.63.2"
          }
        },
        {
          "group": "com.kwad.sdk",
          "module": "kssdk-ad",
          "version": {
            "requires": "3.3.63"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-sigmob-adapter",
          "version": {
            "requires": "4.17.1.1"
          }
        },
        {
          "group": "com.sigmob.sdk",
          "module": "common",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.sigmob.sdk",
          "module": "adsdk",
          "version": {
            "requires": "4.17.1"
          }
        },
        {
          "group": "com.beizi",
          "module": "fusion",
          "version": {
            "requires": "4.90.4.12"
          }
        },
        {
          "group": "com.beizi",
          "module": "adsdk",
          "version": {
            "requires": "3.5.0.11"
          }
        },
        {
          "group": "doublejump.top",
          "module": "channel",
          "version": {
            "requires": "1.1.28"
          }
        },
        {
          "group": "doublejump.top",
          "module": "zhike",
          "version": {
            "requires": "1.1.28"
          }
        },
        {
          "group": "doublejump.top",
          "module": "base",
          "version": {
            "requires": "1.1.13"
          }
        },
        {
          "group": "doublejump.top",
          "module": "adsdk",
          "version": {
            "requires": "1.1.28"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcode",
          "version": {
            "requires": "1.25.8"
          }
        },
        {
          "group": "me.drakeet.support",
          "module": "toastcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "x851cn-1.1.aar",
          "url": "x851cn-1.1.aar",
          "size": 264851,
          "sha512": "cb27d10357c6047b5c76f95d2b323909afa1aaa8141f930a86937cc1d4f95023599ed1056d901edb322dcf7aa77397f8aa162c667a2557f19d6aa384904df7e4",
          "sha256": "8bbb77c0775884035ab949a90b63f29a4feafc46a85e14967aac1bb013639884",
          "sha1": "1a129aafa64cc502dd438f889fd1b4c41f6cdefb",
          "md5": "4eaf4dca03210416b98a93791d3ca0e3"
        }
      ]
    }
  ]
}
