{
  "formatVersion": "1.1",
  "component": {
    "group": "com.x8zs.adsdk",
    "module": "hlx",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fst7vvjembevtnfxhlelotoxdy"
    }
  },
  "variants": [
    {
      "name": "hlxReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hlx-1.1.3.aar",
          "url": "hlx-1.1.3.aar",
          "size": 129701,
          "sha512": "27ca17edc72c8ff3035370f96958c9863ad94171398977cc990fbd9739d4b25c28e0bc0b33ea0e1421f55c4e6a65dc21dbba47a3f3aa685a62d249939d8fea8e",
          "sha256": "db80c21141d4d6946cf3bf617f6a00005a7ad38bb2a0887a12525fbecbb376c3",
          "sha1": "9da53dcabf09b8bad4c843c1d92f1dcefc4cd244",
          "md5": "ce45c759f683c56b35a8be06d790addb"
        }
      ]
    },
    {
      "name": "hlxReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pangle.cn.m",
          "module": "mediation-sdk",
          "version": {
            "requires": "6.2.1.7"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-test-tools",
          "version": {
            "requires": "6.2.1.7"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcode",
          "version": {
            "requires": "1.25.8"
          }
        },
        {
          "group": "me.drakeet.support",
          "module": "toastcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "hlx-1.1.3.aar",
          "url": "hlx-1.1.3.aar",
          "size": 129701,
          "sha512": "27ca17edc72c8ff3035370f96958c9863ad94171398977cc990fbd9739d4b25c28e0bc0b33ea0e1421f55c4e6a65dc21dbba47a3f3aa685a62d249939d8fea8e",
          "sha256": "db80c21141d4d6946cf3bf617f6a00005a7ad38bb2a0887a12525fbecbb376c3",
          "sha1": "9da53dcabf09b8bad4c843c1d92f1dcefc4cd244",
          "md5": "ce45c759f683c56b35a8be06d790addb"
        }
      ]
    }
  ]
}
