{
  "formatVersion": "1.1",
  "component": {
    "group": "com.x8zs.adsdk",
    "module": "hlx",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "tbfxicgbjfamdnit6w324ygxtq"
    }
  },
  "variants": [
    {
      "name": "hlxReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hlx-1.0.aar",
          "url": "hlx-1.0.aar",
          "size": 111177,
          "sha512": "9a098a23871d874e2d354de11ea5cc4217dba2b0f71f142a4725d8bb70dee5be0b1e90f0abd233655609598ebf1e3451f43066fe9e6547bf1a3ab54d98a0fe57",
          "sha256": "89fa633a92c8e3576f20efe5b0e259aedb01a1397ec38018b59688af361ad46f",
          "sha1": "8dce9fc9737d9ce9e111f72d5364e984916e70e5",
          "md5": "5d0a591f2bff5010a89655a644d7f13d"
        }
      ]
    },
    {
      "name": "hlxReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pangle.cn.m",
          "module": "mediation-sdk",
          "version": {
            "requires": "6.2.1.7"
          }
        },
        {
          "group": "com.pangle.cn",
          "module": "mediation-test-tools",
          "version": {
            "requires": "6.2.1.7"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcode",
          "version": {
            "requires": "1.25.8"
          }
        },
        {
          "group": "me.drakeet.support",
          "module": "toastcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "hlx-1.0.aar",
          "url": "hlx-1.0.aar",
          "size": 111177,
          "sha512": "9a098a23871d874e2d354de11ea5cc4217dba2b0f71f142a4725d8bb70dee5be0b1e90f0abd233655609598ebf1e3451f43066fe9e6547bf1a3ab54d98a0fe57",
          "sha256": "89fa633a92c8e3576f20efe5b0e259aedb01a1397ec38018b59688af361ad46f",
          "sha1": "8dce9fc9737d9ce9e111f72d5364e984916e70e5",
          "md5": "5d0a591f2bff5010a89655a644d7f13d"
        }
      ]
    }
  ]
}
